### ISSUE TITLE
sort problems

### ISSUE THREAD

**Issue by mikeryancodes** [appacademy/jump-start#3]
I like the problems where the task is to continually use min or max to construct the result array, but I think it may be tough to do this because modifying the source array to get rid of the maxes and mins may be too complex.  I wish I could do more with this but I don't have a computer here and am on my phone.

**Comment by Haseeb-Qureshi** [comment]
Don't want to teach them deletion, too complicated and easy to mess up. Plus it's not a good approximation of the programming problems we're going to give them.
