### ISSUE TITLE
assessment

### ISSUE THREAD

**Issue by younjiwoo** [appacademy/jump-start#50]
@RyanRHall @akingabramson

"You will have an assessment on the second Monday and Thursday during JumpStart (W2D1 and W2D4). If you receive a passing score on either, your application will be forwarded to our admissions team for a final review. You do not need to attend week 2 if you pass assessment 1."

Does this mean that if I pass the Monday assessment, I do not need to attend the remainder of week 2? Sorry, I just wanted to be clear. Thanks!

**Comment by gbhmt** [comment]
Yep, that is correct.
